server:
  port: 9000

security:
  oauth2:
    resource:
      filter-order: 3
      id: resourceId
    client:
      client-id: clientId
      client-secret: secret
      access_token-validity_seconds: 99999999
      refresh_token-validity_seconds: 99999999
      secret_key: 95kbqeW01lRyw4NslcaUSghSpHVyfLgb4GOEJ9pWJyLtcyT8mfRgtJWEvV2mRI0JIytE72Lk4z70TQ1W

spring:
  data:
    mongodb:
      database: datamarketplace
      host: 192.168.99.102
      port: 27017

logging:
    level:
      org.springframework.root: DEBUG
      org.springframework.web: DEBUG
      org.springframework.security: DEBUG
      org.springframework.data.mongodb: DEBUG